# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openpose_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1470, 847)
        Form.setMinimumSize(QtCore.QSize(1417, 847))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.label = QtGui.QLabel(Form)
        self.label.setAutoFillBackground(True)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.main_Image = QtGui.QLabel(Form)
        self.main_Image.setFrameShape(QtGui.QFrame.Box)
        self.main_Image.setFrameShadow(QtGui.QFrame.Plain)
        self.main_Image.setText(_fromUtf8(""))
        self.main_Image.setScaledContents(False)
        self.main_Image.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.main_Image.setObjectName(_fromUtf8("main_Image"))
        self.verticalLayout.addWidget(self.main_Image)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 23)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(24)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.head_1_text = QtGui.QLabel(Form)
        self.head_1_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_1_text.setObjectName(_fromUtf8("head_1_text"))
        self.verticalLayout_4.addWidget(self.head_1_text)
        self.head_1 = QtGui.QLabel(Form)
        self.head_1.setFrameShape(QtGui.QFrame.Box)
        self.head_1.setText(_fromUtf8(""))
        self.head_1.setScaledContents(True)
        self.head_1.setAlignment(QtCore.Qt.AlignCenter)
        self.head_1.setObjectName(_fromUtf8("head_1"))
        self.verticalLayout_4.addWidget(self.head_1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.head_2_text = QtGui.QLabel(Form)
        self.head_2_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_2_text.setObjectName(_fromUtf8("head_2_text"))
        self.verticalLayout_4.addWidget(self.head_2_text)
        self.head_2 = QtGui.QLabel(Form)
        self.head_2.setFrameShape(QtGui.QFrame.Box)
        self.head_2.setText(_fromUtf8(""))
        self.head_2.setScaledContents(True)
        self.head_2.setAlignment(QtCore.Qt.AlignCenter)
        self.head_2.setObjectName(_fromUtf8("head_2"))
        self.verticalLayout_4.addWidget(self.head_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.head_3_text = QtGui.QLabel(Form)
        self.head_3_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_3_text.setObjectName(_fromUtf8("head_3_text"))
        self.verticalLayout_4.addWidget(self.head_3_text)
        self.head_3 = QtGui.QLabel(Form)
        self.head_3.setFrameShape(QtGui.QFrame.Box)
        self.head_3.setText(_fromUtf8(""))
        self.head_3.setScaledContents(True)
        self.head_3.setAlignment(QtCore.Qt.AlignCenter)
        self.head_3.setObjectName(_fromUtf8("head_3"))
        self.verticalLayout_4.addWidget(self.head_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 6)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 1)
        self.verticalLayout_4.setStretch(5, 6)
        self.verticalLayout_4.setStretch(6, 1)
        self.verticalLayout_4.setStretch(7, 1)
        self.verticalLayout_4.setStretch(8, 6)
        self.verticalLayout_4.setStretch(9, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(24)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.head_4_text = QtGui.QLabel(Form)
        self.head_4_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_4_text.setObjectName(_fromUtf8("head_4_text"))
        self.verticalLayout_3.addWidget(self.head_4_text)
        self.head_4 = QtGui.QLabel(Form)
        self.head_4.setFrameShape(QtGui.QFrame.Box)
        self.head_4.setText(_fromUtf8(""))
        self.head_4.setScaledContents(True)
        self.head_4.setAlignment(QtCore.Qt.AlignCenter)
        self.head_4.setObjectName(_fromUtf8("head_4"))
        self.verticalLayout_3.addWidget(self.head_4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.head_5_text = QtGui.QLabel(Form)
        self.head_5_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_5_text.setObjectName(_fromUtf8("head_5_text"))
        self.verticalLayout_3.addWidget(self.head_5_text)
        self.head_5 = QtGui.QLabel(Form)
        self.head_5.setFrameShape(QtGui.QFrame.Box)
        self.head_5.setText(_fromUtf8(""))
        self.head_5.setScaledContents(True)
        self.head_5.setAlignment(QtCore.Qt.AlignCenter)
        self.head_5.setObjectName(_fromUtf8("head_5"))
        self.verticalLayout_3.addWidget(self.head_5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.head_6_text = QtGui.QLabel(Form)
        self.head_6_text.setAlignment(QtCore.Qt.AlignCenter)
        self.head_6_text.setObjectName(_fromUtf8("head_6_text"))
        self.verticalLayout_3.addWidget(self.head_6_text)
        self.head_6 = QtGui.QLabel(Form)
        self.head_6.setFrameShape(QtGui.QFrame.Box)
        self.head_6.setText(_fromUtf8(""))
        self.head_6.setScaledContents(True)
        self.head_6.setAlignment(QtCore.Qt.AlignCenter)
        self.head_6.setObjectName(_fromUtf8("head_6"))
        self.verticalLayout_3.addWidget(self.head_6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 6)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 6)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 1)
        self.verticalLayout_3.setStretch(8, 6)
        self.verticalLayout_3.setStretch(9, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(24)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.start = QtGui.QPushButton(Form)
        self.start.setShortcut(_fromUtf8(""))
        self.start.setCheckable(False)
        self.start.setObjectName(_fromUtf8("start"))
        self.horizontalLayout_2.addWidget(self.start)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.track_button = QtGui.QPushButton(Form)
        self.track_button.setObjectName(_fromUtf8("track_button"))
        self.horizontalLayout_2.addWidget(self.track_button)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.hand_on = QtGui.QPushButton(Form)
        self.hand_on.setObjectName(_fromUtf8("hand_on"))
        self.horizontalLayout_2.addWidget(self.hand_on)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.box_on = QtGui.QPushButton(Form)
        self.box_on.setObjectName(_fromUtf8("box_on"))
        self.horizontalLayout_2.addWidget(self.box_on)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(2, 6)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(5, 1)
        self.horizontalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(2, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "title", None))
        self.label_4.setText(_translate("Form", "main_image", None))
        self.head_1_text.setText(_translate("Form", "head_1", None))
        self.head_2_text.setText(_translate("Form", "head_2", None))
        self.head_3_text.setText(_translate("Form", "head_3", None))
        self.head_4_text.setText(_translate("Form", "head_4", None))
        self.head_5_text.setText(_translate("Form", "head_5", None))
        self.head_6_text.setText(_translate("Form", "head_6", None))
        self.start.setText(_translate("Form", "start", None))
        self.track_button.setText(_translate("Form", "track_on", None))
        self.hand_on.setText(_translate("Form", "hand_on", None))
        self.box_on.setText(_translate("Form", "box_on", None))

